# Generated by Django 5.2.7 on 2025-10-06 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('verification_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=True, help_text='Allow public verification of this certificate')),
                ('certificate_file', models.FileField(blank=True, help_text='Generated PDF certificate file', null=True, upload_to='certificates/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certifications_certificate',
                'ordering': ['-issue_date'],
                'indexes': [models.Index(fields=['certificate_number'], name='certificati_certifi_a6797e_idx'), models.Index(fields=['verification_code'], name='certificati_verific_b3d402_idx'), models.Index(fields=['issue_date'], name='certificati_issue_d_09a975_idx'), models.Index(fields=['enrollment'], name='certificati_enrollm_50c08c_idx')],
            },
        ),
    ]
